name: genepax311
channels:
- defaults
- conda-forge
dependencies:
- python=3.11
- pip>=20.3.3
- conda>=4.9.2
- pip:
    - "jax[cuda13]"
    - qdax @ git+https://github.com/adaptive-intelligent-robotics/QDax.git@46b8feecae26d79414ce7a1ce731e5cfbeb9837d
    - -r requirements.txt
    - -r requirements-dev.txt
