site_name: genepax
site_description: JAX Accelerated Genetic Programming
site_author: Giorgia Nadizar
site_url: https://giorgia-nadizar.github.io/genepax/

repo_url: https://github.com/giorgia-nadizar/genepax
repo_name: genepax

theme:
  name: readthedocs
  language: en

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - API:
      - Evolution: api/evolution.md
      - Genetic Programming: api/gp.md
      - Supervised Learning: api/supervised_learning.md
